# Generated by Django 2.0.2 on 2018-02-08 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CentreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centreName', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoursesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=50)),
                ('courseImage', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('courseSlogun', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DatesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PromoCodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoCode', models.CharField(max_length=50)),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='studyCategoriesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='SubCourseImagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='media/images')),
            ],
        ),
        migrations.CreateModel(
            name='SubCoursesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructorName', models.CharField(max_length=50)),
                ('rate', models.IntegerField()),
                ('fees', models.CharField(max_length=50)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centre', to='mainApp.CentreModel')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subCourses', to='mainApp.CoursesModel')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11)),
                ('certificate', models.CharField(blank=True, max_length=500, null=True)),
                ('fieldOfStudy', models.ManyToManyField(blank=True, related_name='userCategories', to='mainApp.studyCategoriesModel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subcourseimagesmodel',
            name='subCourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainApp.SubCoursesModel'),
        ),
        migrations.AddField(
            model_name='datesmodel',
            name='subCourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='mainApp.SubCoursesModel'),
        ),
        migrations.AddField(
            model_name='coursesmodel',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='courseCategories', to='mainApp.studyCategoriesModel'),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='promoCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.PromoCodeModel'),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='subCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.SubCoursesModel'),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.UserProfileModel'),
        ),
    ]
