# Generated by Django 2.0.2 on 2018-02-05 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20180205_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CentreImagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='Images')),
            ],
        ),
        migrations.CreateModel(
            name='CentreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centreName', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=500)),
                ('centreImages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.CentreImagesModel')),
            ],
        ),
        migrations.CreateModel(
            name='CoursesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=50)),
                ('courseImage', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('courseSlogun', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DatesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PromoCodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoCode', models.CharField(max_length=50)),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCoursesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructorName', models.CharField(max_length=50)),
                ('rate', models.IntegerField()),
                ('fees', models.CharField(max_length=50)),
                ('subCourseImage', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.CentreModel')),
                ('startingDate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.DatesModel')),
            ],
        ),
        migrations.AlterField(
            model_name='certificatesmodel',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='Certificates'),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='promoCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.PromoCodeModel'),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='subCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.SubCoursesModel'),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.UserProfileModel'),
        ),
    ]
