# Generated by Django 2.0.2 on 2018-02-05 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20180205_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='certificates',
        ),
        migrations.AddField(
            model_name='certificatesmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.UserProfileModel'),
        ),
    ]
