# Generated by Django 2.0.2 on 2018-02-05 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20180205_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcoursesmodel',
            name='centre',
        ),
        migrations.AddField(
            model_name='centremodel',
            name='subCourses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centre', to='mainApp.SubCoursesModel'),
        ),
    ]
