# Generated by Django 2.0.2 on 2018-02-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_subcoursesmodel_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='studyCategoriesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=90)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='major',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='university',
        ),
        migrations.AlterField(
            model_name='centreimagesmodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='certificatesmodel',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='media/certificates'),
        ),
        migrations.AlterField(
            model_name='coursesmodel',
            name='courseImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='subcoursesmodel',
            name='subCourseImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='educationLevel',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='coursesmodel',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='courseCategories', to='mainApp.studyCategoriesModel'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='fieldOfStudy',
            field=models.ManyToManyField(blank=True, null=True, related_name='userCategories', to='mainApp.studyCategoriesModel'),
        ),
    ]
