# Generated by Django 2.0.2 on 2018-02-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20180207_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesmodel',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='courseCategories', to='mainApp.studyCategoriesModel'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='fieldOfStudy',
            field=models.ManyToManyField(blank=True, related_name='userCategories', to='mainApp.studyCategoriesModel'),
        ),
    ]
