# Generated by Django 2.0.2 on 2018-02-07 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20180207_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='educationLevel',
        ),
    ]
