# Generated by Django 2.0.2 on 2018-02-08 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_centremodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCourseImagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='media/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='centreimagesmodel',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='subcoursesmodel',
            name='subCourseImage',
        ),
        migrations.AddField(
            model_name='centremodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
        migrations.DeleteModel(
            name='CentreImagesModel',
        ),
        migrations.AddField(
            model_name='subcourseimagesmodel',
            name='subCourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainApp.SubCoursesModel'),
        ),
    ]
