# Generated by Django 2.0.2 on 2018-02-08 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_auto_20180208_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datesmodel',
            old_name='date',
            new_name='dates',
        ),
        migrations.RemoveField(
            model_name='subcoursesmodel',
            name='startingDate',
        ),
        migrations.AddField(
            model_name='datesmodel',
            name='subCourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.SubCoursesModel'),
        ),
    ]
